Update GitHub Actions to use new bashbrew action
adoptium/containers pull request #317
Opened 2022-11-17 18:41 UTC by tianon

This should fix errors that the old code would've run into thanks to the update to Go 1.18

See https://github.com/docker-library/bashbrew/pull/57 :innocent:

(Pinning this to version v0.1.5 should now also help insulate you from build failures like these in the future!)

2022-11-22 08:13 UTC, karianna commented
@tianon Would you be OK with signing the Eclipse CLA?

2022-11-24 12:44 UTC, gdams approved these changes
LGTM

2022-11-24 12:49 UTC, gdams commented
@tianon in order to commit to the Adoptium project you'll need to sign the ECA (https://adoptium.net/docs/eca-sign-off/)

2022-11-25 13:56 UTC, tellison requested changes
Needs to use action hashcode in preference to version name.

2022-11-25 13:56 UTC, tellison commented on .github/workflows/test-pr.yml
> +      - uses: docker-library/bashbrew@v0.1.5
```suggestion
      - uses: docker-library/bashbrew@ f95be1e3f9aca3109dc8768302c20cf9e01b497f  # v0.1.6
```

2022-11-26 11:25 UTC, zdtsw commented
@tianon still need to have ECA signed

2022-11-28 22:47 UTC, tianon commented
I tried, but my Eclipse Account and my commits/GitHub use different email addresses, so it honestly wasn't worth the hoops to me.  FWIW, I'll happily state publicly that this (trivial) patch is freely usable under CC0 (there's nothing terribly interesting here) -- I figured being the original author of the YAML this was inspired from would probably be enough, but I guess not. :smile:

2022-11-28 22:47 UTC, closed without merging

2022-11-28 23:09 UTC, gdams commented
Sorry that was awkward @tianon, I've raised an identical PR here https://github.com/adoptium/containers/pull/323

2022-11-29 08:38 UTC, tellison commented
+1 thanks for trying Tianon.