--chmod support for COPY and ADD
adoptium/containers pull request #624
Opened 2024-08-06 12:11 UTC by shalk

2024-08-06 16:53 UTC, karianna commented
@shalk Can you sign the Eclipse CLA?

2024-08-09 10:50 UTC, gdams requested changes
We'll have to block this until the default docker version on the GH CI contains this feature:

```output
ERROR: failed to solve: dockerfile parse error on line 103: unknown flag: chmod
```

2024-08-09 10:57 UTC, gdams approved these changes

2024-08-12 21:37 UTC, karianna approved these changes

2024-08-12 21:37 UTC, merged