Initial cut of Docs
adoptium/containers pull request #67
Opened 2021-09-22 08:57 UTC by karianna

2021-09-22 08:58 UTC, gdams approved these changes

2021-09-22 09:28 UTC, timja commented on README.md
> +At the bottom of that edit screen add a title and description for the commit and click on hte _Propose Change_ button.
```suggestion
At the bottom of that edit screen add a title and description for the commit and click on the _Propose Change_ button.
```

2021-09-22 14:49 UTC, sxa reviewed
Do we have any sort of overview of what the two scripts `update_all.sh` and perhaps also the manifest update one do? Ideally we need something like "The scripts checks for X,Y,Z and updates A,B,C". This is useful to know when the process needs to be run.

Might also be useful to flesh out the "diff output created"  could be fleshed out - is that just a normal review of what's in the PR?

2021-09-24 08:13 UTC, tellison commented
ECA check fails on [anonymous gdams](https://github.com/adoptium/containers/pull/67/commits/d1cb554b4b02fe11d88bfa04f0461f59d05c636a) change

2021-09-29 09:47 UTC, tellison commented on README.md
> +should not be read aas a traditional PR (since Docker Hub bots do move things around, so you may see what looks like odd deletions)
typo "aas" -> "as"

2021-09-29 09:47 UTC, tellison commented on README.md
> +but as a sanity check to make sure you see the platoforms/architectures that you expect.
typo "platoforms" -> "platforms"

2021-09-29 09:48 UTC, karianna commented on README.md
> +should not be read aas a traditional PR (since Docker Hub bots do move things around, so you may see what looks like odd deletions)
Fixed thanks

2021-09-29 09:49 UTC, karianna commented on README.md
> +but as a sanity check to make sure you see the platoforms/architectures that you expect.
Fixed thanks.

2021-09-29 12:12 UTC, sxa requested changes

2021-09-29 12:12 UTC, sxa commented on README.md
> +but as a sanity check to make sure you see the platoforms/architectures that you expect.
Hmmm github isn't giving me the option for suggesting changes on this, but typo here "platoforms". Once that's addressed (and the ECA check failure resolved) I'm happy with this now :-)

2021-09-29 12:13 UTC, sxa commented on README.md
> +but as a sanity check to make sure you see the platoforms/architectures that you expect.
Ah ignore that - I see it was changed in a subsequent commit.

2021-09-29 12:13 UTC, sxa approved these changes
LGTM but the ECA check failure should be addressed prior to merging

2021-09-30 08:43 UTC, merged